### ISSUE TITLE
Accessing a local github appliance

### ISSUE THREAD

**Issue by adrianblakey** [pentestfail/TA-Github#8]
How do I configure the api to access a local github repo. that is accessible as a https URL?

Specifically where do I put the TLS cert? 

And should I configure the switch to use the v3 api?

**Comment by adrianblakey** [comment]
How to I configure the certs?

I concatenated the pem from the git server onto the  end of: /opt/splunk/lib/python2.7/site-packages/requests/cacert.pem

However this messages still appears in the log:

11-13-2018 12:30:34.717 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py" ERRORlocal variable 'r_status' referenced before assignment
11-13-2018 12:33:20.507 -0800 ERROR AuthenticationManagerSplunk - Login failed. Incorrect login for user: admin
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py" Traceback (most recent call last):
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py"   File "/opt/splunk/etc/apps/TA-Github/bin/ta_github/modinput_wrapper/base_modinput.py", line 127, in stream_events
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py"     self.collect_events(ew)
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py"   File "/opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py", line 72, in collect_events
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py"     input_module.collect_events(self, ew)
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py"   File "/opt/splunk/etc/apps/TA-Github/bin/input_module_github_api_repos_commits.py", line 135, in collect_events
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py"     raise error
11-13-2018 12:36:32.573 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py" SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:603)
11-13-2018 12:36:32.597 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_commits.py" ERROR[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:603)
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py" Traceback (most recent call last):
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py"   File "/opt/splunk/etc/apps/TA-Github/bin/ta_github/modinput_wrapper/base_modinput.py", line 127, in stream_events
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py"     self.collect_events(ew)
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py"   File "/opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py", line 72, in collect_events
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py"     input_module.collect_events(self, ew)
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py"   File "/opt/splunk/etc/apps/TA-Github/bin/input_module_github_api_repos_stats.py", line 109, in collect_events
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py"     helper.log_error("input_type={0:s} input={1:s} status_code={2:d} reason='{3:s}' error='{4:s}'".format(inputtype,inputname,r_status,r_reason,error))
11-13-2018 12:36:34.637 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py" UnboundLocalError: local variable 'r_status' referenced before assignment
11-13-2018 12:36:34.660 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/TA-Github/bin/github_api_repos_stats.py" ERRORlocal variable 'r_status' referenced before assignment

**Comment by adrianblakey** [comment]
I found the cacerts file in /opt/splunk/lib/python2.7/site-packages/requests/cacert.pem
Appending my cert to it seemed to do the trick - for a while. Until Splunk decided it did not like this file anymore:

11-14-2018 10:17:26.996 -0800 WARN  InstalledFilesHashChecker - An installed file="/opt/splunk/lib/python2.7/site-packages/requests/cacert.pem" did not pass hash-checking due to reason="content mismatch"

And now things are back to not working ...

**Comment by adrianblakey** [comment]
Looks like the real location is:

/opt/splunk/etc/apps/TA-Github/bin/ta_github/requests/cacert.pem

**Comment by adrianblakey** [comment]
This has not fixed the issue - I was mistaken.

I just gave up and edited to code to use TlsVerify=False.
